import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    home: 'Home',
    properties: 'Properties',
    services: 'Services',
    about: 'About',
    contact: 'Contact',
    m1: "🏆 Bin Thani Real Estate — Sharjah's Most Trusted Agency",
    m2: "🏠 Premium Properties in Sharjah",
    m3: "📞 Book a Free Consultation Today",
    m4: "✨ Off-Plan & Ready Properties Available Now",
    heroTagline: 'Premium Real Estate',
    heroLine1: 'Find Your',
    heroLine2: 'Dream Home',
    heroSubtitle: 'Discover exclusive luxury properties across UAE',
    whatWeOffer: 'What We Offer',
    ourServices: 'Our Services',
    featuredProperties: 'Featured Properties',
    handpicked: 'Handpicked',
    exploreLuxury: 'Explore our handpicked luxury properties across UAE.',
    viewAllProperties: 'View All Properties',
    readyToFind: 'Ready to Find Your Dream Home?',
    findPerfect: 'Let our experts help you find the perfect property',
    browseProperties: 'Browse Properties',
    findDreamProperty: 'Find Your Dream Property',
    browseExclusive: "Browse our exclusive collection of luxury properties across UAE",
    searchPlaceholder: 'Search by area, project, or property name...',
    allTypes: 'All Types',
    allAreas: 'All Areas',
    anyBedrooms: 'Any',
    minPrice: 'Min',
    maxPrice: 'Max',
    allStatus: 'All Status',
    available: 'Available',
    offPlan: 'Off-Plan',
    sold: 'Sold',
    clearAll: 'Clear All',
    propertiesFound: 'Properties Found',
    noPropertiesFound: 'No properties found',
    tryAdjustingFilters: 'Try adjusting your filters to see more results',
    beds: 'Beds',
    baths: 'Baths',
    sqft: 'sqft',
    parking: 'Parking',
    viewDetails: 'View Details',
    clearSearch: 'Clear Search',
    loadingProps: 'Loading properties...',
    noMatchFor: "We couldn't find any properties matching",
    adjustFilters: 'Try different keywords or adjust your filters.',
    backToProperties: 'Back to Properties',
    description: 'Description',
    amenities: 'Amenities',
    location: 'Location',
    locationOnMap: 'Location on Map',
    mortgageCalculator: 'Mortgage Calculator',
    propertyPrice: 'Property Price',
    downPayment: 'Down Payment',
    interestRate: 'Interest Rate',
    loanTerm: 'Loan Term',
    monthlyPayment: 'Monthly Payment',
    loanAmount: 'Loan Amount',
    interestedProperty: 'Interested in this property?',
    getInTouch: 'Get in touch with our team',
    requestDetails: 'Request Details',
    yourName: 'Your Name',
    phoneNumber: 'Phone Number',
    emailAddress: 'Email Address',
    yourMessage: 'Your Message',
    sendEnquiry: 'Send Enquiry',
    developer: 'Developer',
    contactUs: 'Contact Us',
    builtIn: 'Built in',
    floorPlan: 'Floor Plan',
    propertyNotFound: 'Property Not Found',
    loadingProperty: 'Loading property...',
    servicesHeroTitle: 'Our Services',
    servicesHeroSubtitle: 'Excellence in Every Transaction',
    buyProperty: 'Buy Property',
    buyPropertyDesc: 'Find your dream home from our curated selection of luxury properties across UAE',
    rentProperty: 'Rent Property',
    rentPropertyDesc: 'Premium rental options for short-term and long-term leases',
    investment: 'Investment Advisory',
    investmentDesc: 'Expert guidance on high-yield investment opportunities in UAE real estate',
    sellProperty: 'Sell Property',
    sellPropertyDesc: 'Sell your property at the best market price with our expert marketing',
    propertyManagement: 'Property Management',
    propertyManagementDesc: 'Full-service property management for investors and landlords',
    mortgageAdvisory: 'Mortgage Advisory',
    mortgageAdvisoryDesc: 'Professional assistance with financing options and mortgage approvals',
    learnMore: 'Learn More',
    aboutHeroTitle: 'About Bin Thani',
    aboutHeroSubtitle: 'Excellence in Real Estate Since 2010',
    founderLabel: 'Founder & CEO',
    founderName: 'Essa bin Rashid bin Thani',
    founderBio1: 'Essa bin Rashid bin Thani is the visionary Founder and CEO of Bin Thani Real Estate. With over two decades of profound experience in the UAE real estate sector, he has cultivated a reputation for excellence, integrity, and an unparalleled understanding of the luxury market landscape.',
    founderBio2: 'His leadership has transformed Bin Thani Real Estate into a prestigious brand synonymous with trust and sophistication. Specializing in high-end residential and commercial developments, Essa\'s strategic vision focuses on delivering exceptional value and bespoke experiences to a discerning global clientele.',
    founderBio3: 'Under his guidance, the firm continues to pioneer innovative real estate solutions across Sharjah and the Northern Emirates, consistently setting new benchmarks for quality and service in the industry.',
    propertiesSold: 'Properties Sold',
    yearsExperience: 'Years Experience',
    happyClients: 'Happy Clients',
    developers: 'Developers',
    whyUs: 'Why Choose Us',
    ourValues: 'Our Values',
    expertKnowledge: 'Expert Knowledge',
    expertKnowledgeDesc: 'In-depth understanding of the UAE property market across all emirates',
    personalizedService: 'Personalized Service',
    personalizedServiceDesc: 'Tailored solutions to meet your unique property needs and goals',
    trustedPartner: 'Trusted Partner',
    trustedPartnerDesc: 'Transparent, ethical, and professional service at all times',
    readyToWork: 'Ready to Work With Us?',
    getInTouchDesc: 'Contact our team of experts today',
    viewProperties: 'View Properties',
    contactHeroTitle: 'Contact Us',
    contactHeroSubtitle: "We're Here to Help",
    visitUs: 'Visit Us',
    sharjahOffice: 'Muwaileh Sharjah, United Arab Emirates',
    callUs: 'Call Us',
    emailUs: 'Email Us',
    developerPartners: 'Our Developer Partners',
    developerSubtitle: "Explore exclusive projects from Sharjah's top developers",
    loadingProjects: 'Loading projects...',
    viewProject: 'View Project',
    luxuryRealEstate: 'Luxury Real Estate Experts in Sharjah & UAE. Providing premium property solutions for over 15 years.',
    quickLinks: 'Quick Links',
    newsletter: 'Newsletter',
    yourEmail: 'Your Email',
    join: 'Join',
    copyright: 'All rights reserved.',
    cookieText: 'We use cookies to ensure you get the best experience on our website.',
    accept: 'Accept',
    privacyPolicy: 'Privacy Policy',
    loading: 'Loading...',
    search: 'Search',
    buyDesc: 'Find your dream home from our curated selection of luxury properties',
    rentDesc: 'Premium rental options for short and long-term leases',
    investDesc: 'High-yield investment opportunities in UAE real estate',
    offPlanService: 'Off-Plan',
    offPlanDesc: 'Latest off-plan developments with attractive payment plans',
    aboutProject: 'About Project',
    skip: 'Skip',
    submit: 'Submit',
    typeMessage: 'Type a message...',
    onlineSupport: 'Online Support',
    send: 'Send',
    backToHome: 'Back to Home',
    filters: 'Filters',
    propertyType: 'Property Type',
    statusLabel: 'Status',
    bedroomsLabel: 'Bedrooms',
    buy: 'Buy',
    rent: 'Rent',
    all: 'All',
    filterByArea: 'Filter by Area',
    aboutUs: 'About Us',
    ourStory: 'Our Story',
    mission: 'Our Mission',
    vision: 'Our Vision',
    backToProjects: 'Back to Projects',
    successMsg: 'Sent successfully! We will contact you soon.',
    allDevelopers: 'All Developers',
    searchProperties: 'Search properties...'
},
  ar: {
    home: 'الرئيسية',
    properties: 'العقارات',
    services: 'الخدمات',
    about: 'من نحن',
    contact: 'اتصل بنا',
    m1: "🏆 بن ثاني للعقارات — الوكالة الأكثر موثوقية في الشارقة",
    m2: "🏠 عقارات فاخرة في الشارقة",
    m3: "📞 احجز استشارة مجانية اليوم",
    m4: "✨ عقارات جاهزة وعلى الخريطة متاحة الآن",
    heroTagline: 'عقارات فاخرة',
    heroLine1: 'اعثر على',
    heroLine2: 'منزل أحلامك',
    heroSubtitle: 'اكتشف عقارات فاخرة حصرية في جميع أنحاء الإمارات',
    whatWeOffer: 'ما نقدمه',
    ourServices: 'خدماتنا',
    featuredProperties: 'العقارات المميزة',
    handpicked: 'مختارة بعناية',
    exploreLuxury: 'استكشف عقاراتنا الفاخرة المختارة في جميع أنحاء الإمارات.',
    viewAllProperties: 'عرض جميع العقارات',
    readyToFind: 'جاهز للعثور على منزل أحلامك؟',
    findPerfect: 'دع خبراءنا يساعدونك في العثور على العقار المثالي',
    browseProperties: 'تصفح العقارات',
    findDreamProperty: 'ابحث عن عقار أحلامك',
    browseExclusive: "تصفح مجموعتنا الحصرية من العقارات الفاخرة في جميع أنحاء الإمارات",
    searchPlaceholder: 'ابحث حسب المنطقة أو المشروع أو اسم العقار...',
    allTypes: 'جميع الأنواع',
    allAreas: 'جميع المناطق',
    anyBedrooms: 'أي عدد',
    minPrice: 'الحد الأدنى',
    maxPrice: 'الحد الأقصى',
    allStatus: 'جميع الحالات',
    available: 'متاح',
    offPlan: 'على الخريطة',
    sold: 'مباع',
    clearAll: 'مسح الكل',
    propertiesFound: 'عقارات وجدت',
    noPropertiesFound: 'لم يتم العثور على عقارات',
    tryAdjustingFilters: 'حاول تعديل الفلاتر لرؤية المزيد من النتائج',
    beds: 'غرف',
    baths: 'حمامات',
    sqft: 'قدم مربع',
    parking: 'موقف',
    viewDetails: 'عرض التفاصيل',
    clearSearch: 'مسح البحث',
    loadingProps: 'جاري تحميل العقارات...',
    noMatchFor: "لم نتمكن من العثور على أي عقارات تطابق",
    adjustFilters: 'جرب كلمات رئيسية مختلفة أو عدل الفلاتر.',
    backToProperties: 'العودة للعقارات',
    description: 'الوصف',
    amenities: 'المرافق',
    location: 'الموقع',
    locationOnMap: 'الموقع على الخريطة',
    mortgageCalculator: 'حاسبة التمويل العقاري',
    propertyPrice: 'سعر العقار',
    downPayment: 'الدفعة الأولى',
    interestRate: 'نسبة الفائدة',
    loanTerm: 'مدة القرض',
    monthlyPayment: 'الدفعة الشهرية',
    loanAmount: 'مبلغ القرض',
    interestedProperty: 'مهتم بهذا العقار؟',
    getInTouch: 'تواصل مع فريقنا',
    requestDetails: 'طلب التفاصيل',
    yourName: 'اسمك',
    phoneNumber: 'رقم الهاتف',
    emailAddress: 'البريد الإلكتروني',
    yourMessage: 'رسالتك',
    sendEnquiry: 'إرسال الاستفسار',
    developer: 'المطور',
    contactUs: 'اتصل بنا',
    builtIn: 'بني في',
    floorPlan: 'مخطط الطابق',
    propertyNotFound: 'العقار غير موجود',
    loadingProperty: 'جاري تحميل العقار...',
    servicesHeroTitle: 'خدماتنا',
    servicesHeroSubtitle: 'التميز في كل صفقة',
    buyProperty: 'شراء عقار',
    buyPropertyDesc: 'اعثر على منزل أحلامك من تشكيلتنا المختارة من العقارات الفاخرة في الإمارات',
    rentProperty: 'استئجار عقار',
    rentPropertyDesc: 'خيارات إيجار مميزة للإيجارات قصيرة وطويلة الأمد',
    investment: 'الاستشارات الاستثمارية',
    investmentDesc: 'توجيهات خبيرة حول الفرص الاستثمارية عالية العائد في عقارات الإمارات',
    sellProperty: 'بيع عقار',
    sellPropertyDesc: 'بع عقارك بأفضل سعر في السوق مع تسويقنا الخبير',
    propertyManagement: 'إدارة العقارات',
    propertyManagementDesc: 'خدمة كاملة لإدارة العقارات للمستثمرين والملاك',
    mortgageAdvisory: 'استشارات التمويل',
    mortgageAdvisoryDesc: 'مساعدة احترافية في خيارات التمويل والموافقات العقارية',
    learnMore: 'لمعرفة المزيد',
    aboutHeroTitle: 'عن بن ثاني',
    aboutHeroSubtitle: 'التميز في العقارات منذ عام 2010',
    founderLabel: 'المؤسس والرئيس التنفيذي',
    founderName: 'عيسى بن راشد بن ثاني',
    founderBio1: 'عيسى بن راشد بن ثاني هو المؤسس والرئيس التنفيذي صاحب الرؤية لشركة بن ثاني للعقارات. مع أكثر من عقدين من الخبرة العميقة في قطاع العقارات في دولة الإمارات العربية المتحدة، نجح في بناء سمعة قائمة على التميز والنزاهة والفهم العميق لسوق العقارات الفاخرة.',
    founderBio2: 'حولت قيادته شركة بن ثاني للعقارات إلى علامة تجارية مرموقة مرادفة للثقة والرقي. يتخصص عيسى في التطويرات السكنية والتجارية الراقية، وتركز رؤيته الاستراتيجية على تقديم قيمة استثنائية وتجارب مخصصة لنخبة العملاء العالميين.',
    founderBio3: 'تحت توجيهه، تواصل الشركة ريادة الحلول العقارية المبتكرة في الشارقة والإمارات الشمالية، وتضع باستمرار معايير جديدة للجودة والخدمة في هذا القطاع.',
    propertiesSold: 'عقار تم بيعه',
    yearsExperience: 'عاماً من الخبرة',
    happyClients: 'عميل سعيد',
    developers: 'مطور عقاري',
    whyUs: 'لماذا تختارنا',
    ourValues: 'قيمنا',
    expertKnowledge: 'خبرة واسعة',
    expertKnowledgeDesc: 'فهم عميق لسوق العقارات في دولة الإمارات في جميع الإمارات',
    personalizedService: 'خدمة مخصصة',
    personalizedServiceDesc: 'حلول مصممة لتلبية احتياجاتك وأهدافك العقارية الفريدة',
    trustedPartner: 'شريك موثوق',
    trustedPartnerDesc: 'خدمة شفافة وأخلاقية واحترافية في جميع الأوقات',
    readyToWork: 'جاهز للعمل معنا؟',
    getInTouchDesc: 'اتصل بفريق الخبراء لدينا اليوم',
    viewProperties: 'عرض العقارات',
    contactHeroTitle: 'اتصل بنا',
    contactHeroSubtitle: 'نحن هنا للمساعدة',
    visitUs: 'زورونا',
    sharjahOffice: 'مويلح الشارقة، الإمارات العربية المتحدة',
    callUs: 'اتصل بنا',
    emailUs: 'راسلنا',
    developerPartners: 'شركاؤنا من المطورين',
    developerSubtitle: 'استكشف المشاريع الحصرية من كبار المطورين في الشارقة',
    loadingProjects: 'جاري تحميل المشاريع...',
    viewProject: 'عرض المشروع',
    luxuryRealEstate: 'خبراء العقارات الفاخرة في الشارقة والإمارات. نقدم حلول عقارية فاخرة لأكثر من ١٥ عاماً.',
    quickLinks: 'روابط سريعة',
    newsletter: 'النشرة الإخبارية',
    yourEmail: 'بريدك الإلكتروني',
    join: 'انضم',
    copyright: 'جميع الحقوق محفوظة.',
    cookieText: 'نستخدم ملفات تعريف الارتباط لضمان حصولك على أفضل تجربة على موقعنا.',
    accept: 'قبول',
    privacyPolicy: 'سياسة الخصوصية',
    loading: 'جاري التحميل...',
    search: 'بحث',
    buyDesc: 'ابحث عن منزل أحلامك من تشكيلتنا المختارة من العقارات الفاخرة',
    rentDesc: 'خيارات إيجار مميزة للإيجارات قصيرة وطويلة الأمد',
    investDesc: 'فرص استثمارية عالية العائد في عقارات الإمارات',
    offPlanService: 'على الخريطة',
    offPlanDesc: 'أحدث المشاريع على الخريطة مع خطط سداد جذابة',
    aboutProject: 'عن المشروع',
    skip: 'تخطي',
    submit: 'إرسال',
    typeMessage: 'اكتب رسالة...',
    onlineSupport: 'الدعم المباشر',
    send: 'إرسال',
    backToHome: 'العودة للرئيسية',
    filters: 'الفلاتر',
    propertyType: 'نوع العقار',
    statusLabel: 'الحالة',
    bedroomsLabel: 'غرف النوم',
    buy: 'شراء',
    rent: 'إيجار',
    all: 'الكل',
    filterByArea: 'تصفية حسب المنطقة',
    aboutUs: 'من نحن',
    ourStory: 'قصتنا',
    mission: 'مهمتنا',
    vision: 'رؤيتنا',
    backToProjects: 'العودة للمشاريع',
    successMsg: 'تم الإرسال بنجاح! سنتواصل معك قريباً.',
    allDevelopers: 'جميع المطورين',
    searchProperties: 'ابحث عن عقارات...',
    'sea view': 'إطلالة على البحر',
    'private terrace': 'شرفة خاصة',
    'concierge': 'بواب',
    'balcony': 'شرفة',
    'gym': 'صالة رياضية',
    'pool': 'مسبح',
    'community pool': 'مسبح مجتمعي',
    'park': 'حديقة',
    'marina view': 'إطلالة المارينا',
    'private beach': 'شاطئ خاص',
    'golf view': 'إطلالة الجولف',
    'city view': 'إطلالة المدينة',
    '24/7 security': 'أمن 24/7',
    'smart home': 'منزل ذكي',
    'spa': 'منتجع صحي',
    'beach access': 'وصول للشاطئ',
    'car-free community': 'مجتمع بلا سيارات',
    'retail boulevard': 'بوليفارد التسوق',
    'swimming pools': 'مسابح',
    'kids play areas': 'مناطق لعب الأطفال',
    'underground parking': 'مواقف تحت الأرض',
    'crystal lagoon': 'بحيرة كريستالية',
    'smart home features': 'ميزات المنزل الذكي',
    'community mall': 'مركز تجاري',
    'sports facilities': 'مرافق رياضية',
    'madar family complex': 'مجمع مدار العائلي',
    'naseej cultural district': 'حي نسيج الثقافي',
    'business park': 'مجمع الأعمال',
    'boulevard retail': 'تسوق البوليفارد',
    'forested community': 'مجتمع مشجر',
    'cycling track': 'مسار دراجات',
    'zad food village': 'قرية زاد للمطاعم',
    'adventure park': 'حديقة مغامرات',
    'waterfront promenade': 'ممشى الواجهة المائية',
    'boutique retail': 'محال بوتيك',
    'infinity pools': 'مسابح إنفينيتي',
    'premium restaurants': 'مطاعم فاخرة',
    'sky gardens': 'حدائق معلقة',
    'luxury spa': 'سبا فاخر',
    'private beaches': 'شواطئ خاصة',
    'marina': 'مارينا',
    'water park': 'حديقة مائية',
    'luxury hotels': 'فنادق فاخرة',
    'home theater': 'سينما منزلية',
    'fully furnished': 'مفروش بالكامل',
    'high roi': 'عائد استثماري عالي',
    'retail shops': 'محلات تجارية',
    'low-rise villages': 'قرى منخفضة الارتفاع',
    'boutique dining': 'مطاعم راقية',
    'marina access': 'وصول للمارينا',
    'private pool': 'مسبح خاص',
    'home cinema': 'سينما منزلية',
    'zaha hadid design': 'تصميم زها حديد',
    'net-zero ready': 'جاهز لانعدام الانبعاثات',
    'smart tech': 'تكنولوجيا ذكية',
    'parks': 'حدائق',
    'retail hub': 'مركز تسوق',
    'swimming pool': 'مسبح',
    'kids play area': 'منطقة لعب أطفال',
    'retail outlets': 'محلات تجارية',
    'restaurants and cafes': 'مطاعم ومقاهي',
    'covered parking': 'موقف مغطى',
    'landscaped gardens': 'حدائق منسقة',
    'community clubhouse': 'نادي مجتمعي',
    'walking and cycling trails': 'مسارات مشي ودراجات',
    'community parks': 'حدائق مجتمعية',
    'pet friendly areas': 'مناطق صديقة للحيوانات الأليفة',
    'contact for details': 'تواصل لمعرفة السعر'
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('binthani-lang');
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('binthani-lang', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
    document.body.className = language === 'ar' ? 'rtl-ready' : 'ltr-ready';
    
    // Update font based on language
    if (language === 'ar') {
      document.body.style.fontFamily = "'Noto Sans Arabic', sans-serif";
    } else {
      document.body.style.fontFamily = "'DM Sans', sans-serif";
    }
  }, [language]);

  const t = (key) => {
    if (!translations[language]) return key;
    return translations[language][key] || translations['en'][key] || key;
  };

  const getContent = (item, key) => {
    if (!item) return '';
    const arKey = `${key}_ar`;
    if (language === 'ar' && item[arKey]) return item[arKey];
    
    const val = item[key] || '';
    
    if (language === 'ar') {
        const commonMap = {
            'Sharjah': 'الشارقة',
            'Dubai': 'دبي',
            'Aljada': 'الجادة',
            'Masaar': 'مسار',
            'Maryam Island': 'جزيرة مريم',
            'Muwaileh': 'مويلحة',
            'Tilal City': 'مدينة تلال',
            'Ready': 'جاهز',
            'Off-Plan': 'على الخريطة',
            'Sold': 'مباع',
            'Buy': 'شراء',
            'Rent': 'إيجار',
            'Yearly': 'سنوي',
            'Monthly': 'شهري',
            'Arada': 'أراداء',
            'Shurooq': 'شروق',
            'Eagle Hills': 'إيجل هيلز',
            'Alef Group': 'مجموعة ألف',
            'Tiger Group': 'مجموعة تايجر',
            'Tiger Sky Tower': 'تايجر سكاي تاور',
            'Joud Tower': 'برج جود',
            'Sharjah Garden City': 'مدينة الشارقة للحدائق',
            'Al Tay Hills': 'تلال الطي',
            'Qasba Mall & Towers': 'مول وأبراج القصبة',
            'Hawa Residence': 'هاوا ريزيدنس',
            'District 11': 'ديستريكت 11',
            'Al Belaida, Sharjah': 'البليدة، الشارقة',
            'Al Tay, Sharjah': 'الطي، الشارقة',
            'Qasba Canal, Sharjah': 'قناة القصبة، الشارقة',
            'Sheikh Mohammed bin Zayed Road, Sharjah': 'شارع الشيخ محمد بن زايد، الشارقة',
            'Manazil': 'منازل',
            'Al Marwan': 'المروان',
            'Shoumous': 'شموس'
        };
        if (commonMap[val]) return commonMap[val];
    }
    
    return val;
  };

  const toggleLanguage = () => setLanguage(prev => prev === 'en' ? 'ar' : 'en');

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, toggleLanguage, getContent }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
