require('dotenv').config({ path: '/Users/user/Desktop/Website/Bin Thani Website/server/.env' });
const { createClient } = require('@supabase/supabase-js');

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_KEY;

const supabase = createClient(supabaseUrl, supabaseKey);

async function fixSchema() {
    console.log('🔧 Fixing Supabase schema...');

    // 1. Create developers table if it doesn't exist
    console.log('📋 Ensuring developers table exists...');
    const { error: devTableError } = await supabase.rpc('exec_sql', { 
        sql_query: `
            CREATE TABLE IF NOT EXISTS developers (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL UNIQUE,
                name_ar TEXT,
                logo TEXT,
                tagline TEXT,
                tagline_ar TEXT,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
            );
            
            -- Enable RLS
            ALTER TABLE developers ENABLE ROW LEVEL SECURITY;
            
            -- Create policy if not exists
            DO $$ 
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access' AND tablename = 'developers') THEN
                    CREATE POLICY "Public Access" ON developers FOR ALL USING (true);
                END IF;
            END $$;
        `
    });

    if (devTableError) {
        console.log('   Note: RPC exec_sql failed, trying direct table check and column additions...');
    }

    // 2. Add missing columns to properties table
    console.log('📋 Adding missing columns to properties...');
    const columnsToAdd = [
        { name: 'title_ar', type: 'TEXT' },
        { name: 'description_ar', type: 'TEXT' },
        { name: 'location_ar', type: 'TEXT' },
        { name: 'status_ar', type: 'TEXT' },
        { name: 'developer_ar', type: 'TEXT' },
        { name: 'views', type: 'INTEGER DEFAULT 0' }
    ];

    for (const col of columnsToAdd) {
        try {
            const { error } = await supabase.rpc('exec_sql', {
                sql_query: `ALTER TABLE properties ADD COLUMN IF NOT EXISTS ${col.name} ${col.type};`
            });
            if (error) throw error;
            console.log(`   ✅ Added/Checked column: ${col.name}`);
        } catch (e) {
            console.log(`   ⚠️ Failed to add column ${col.name}: ${e.message}`);
        }
    }

    // 3. Fallback: If RPC is not available, we have to tell the user to run SQL manually
    console.log('\n🚀 Final verification of schema...');
    const { error: finalCheck } = await supabase.from('developers').select('*').limit(1);
    if (finalCheck) {
        console.log('❌ Still having issues with developers table:', finalCheck.message);
        console.log('\n👉 PLEASE RUN THIS SQL IN SUPABASE DASHBOARD:');
        console.log(`
            CREATE TABLE IF NOT EXISTS developers (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL UNIQUE,
                name_ar TEXT,
                logo TEXT,
                tagline TEXT,
                tagline_ar TEXT,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
            );
            ALTER TABLE developers ENABLE ROW LEVEL SECURITY;
            CREATE POLICY "Allow all for developers" ON developers FOR ALL USING (true);
            
            ALTER TABLE properties ADD COLUMN IF NOT EXISTS title_ar TEXT;
            ALTER TABLE properties ADD COLUMN IF NOT EXISTS description_ar TEXT;
            ALTER TABLE properties ADD COLUMN IF NOT EXISTS location_ar TEXT;
            ALTER TABLE properties ADD COLUMN IF NOT EXISTS status_ar TEXT;
            ALTER TABLE properties ADD COLUMN IF NOT EXISTS developer_ar TEXT;
            ALTER TABLE properties ADD COLUMN IF NOT EXISTS views INTEGER DEFAULT 0;
        `);
    } else {
        console.log('✅ Schema seems healthy!');
    }
}

fixSchema();
