-- =====================================================
-- BIN THANI REAL ESTATE - MASTER TELEGRAM NOTIFICATION SYSTEM
-- Run this in Supabase SQL Editor
-- =====================================================

-- 1. Enable the pg_net extension to allow making HTTP requests from Postgres
CREATE EXTENSION IF NOT EXISTS pg_net;

-- 2. Master notification function
CREATE OR REPLACE FUNCTION public.notify_telegram_master()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  telegram_token TEXT := '8730614252:AAGuV_V_iHfdmVrfiol_6fCuHCrTEboYyjw';
  chat_id TEXT := '-1003887183193';
  payload JSONB;
  message TEXT;
  table_name TEXT;
  emoji TEXT;
BEGIN
  table_name := TG_TABLE_NAME;
  payload := to_jsonb(NEW);
  
  -- Set Emoji based on table
  CASE table_name
    WHEN 'leads' THEN emoji := '🎯';
    WHEN 'properties' THEN emoji := '🏠';
    WHEN 'developers' THEN emoji := '🏗️';
    WHEN 'blog_posts' THEN emoji := '📰';
    WHEN 'chat_messages' THEN emoji := '🤖';
    ELSE emoji := '🔔';
  END CASE;

  -- Construct a summary message
  message := emoji || ' *New Data in ' || INITCAP(table_name) || '!*' || E'\n\n';
  
  -- Add formatted details based on table type
  IF table_name = 'leads' THEN
    message := message || '👤 *Name:* ' || COALESCE(payload->>'name', 'N/A') || E'\n' ||
               '📞 *Phone:* ' || COALESCE(payload->>'phone', 'N/A') || E'\n' ||
               '📧 *Email:* ' || COALESCE(payload->>'email', 'N/A') || E'\n' ||
               '📍 *Area:* ' || COALESCE(payload->>'area', 'N/A') || E'\n' ||
               '💰 *Budget:* ' || COALESCE(payload->>'budget', 'N/A') || E'\n' ||
               '🌐 *Source:* ' || COALESCE(payload->>'source', 'Website');
  ELSIF table_name = 'properties' THEN
    message := message || '🏗️ *Property:* ' || COALESCE(payload->>'title', 'Untitled') || E'\n' ||
               '📍 *Location:* ' || COALESCE(payload->>'location', 'N/A') || E'\n' ||
               '💰 *Price:* ' || COALESCE(payload->>'price', 'N/A') || E'\n' ||
               '📏 *Area:* ' || COALESCE(payload->>'area', 'N/A');
  ELSIF table_name = 'developers' THEN
    message := message || '🏢 *Developer:* ' || COALESCE(payload->>'name', 'N/A') || E'\n' ||
               '📝 *Tagline:* ' || COALESCE(payload->>'tagline', 'N/A');
  ELSIF table_name = 'chat_messages' THEN
    message := message || '💬 *User:* ' || COALESCE(payload->>'user_message', 'N/A') || E'\n' ||
               '🤖 *Bot:* ' || LEFT(COALESCE(payload->>'bot_response', 'N/A'), 100) || '...';
  ELSE
    -- Generic format for any other table
    message := message || 'New row added to ' || table_name || ' with ID ' || COALESCE(payload->>'id', 'unknown');
  END IF;

  -- Send to Telegram
  PERFORM net.http_post(
    url := 'https://api.telegram.org/bot' || telegram_token || '/sendMessage',
    body := jsonb_build_object(
      'chat_id', chat_id,
      'text', message,
      'parse_mode', 'Markdown'
    )
  );
  
  RETURN NEW;
END;
$$;

-- 3. Create Triggers for ALL tables
DROP TRIGGER IF EXISTS on_lead_added_telegram ON public.leads;
CREATE TRIGGER on_lead_added_telegram AFTER INSERT ON public.leads FOR EACH ROW EXECUTE FUNCTION public.notify_telegram_master();

DROP TRIGGER IF EXISTS on_property_added_telegram ON public.properties;
CREATE TRIGGER on_property_added_telegram AFTER INSERT ON public.properties FOR EACH ROW EXECUTE FUNCTION public.notify_telegram_master();

DROP TRIGGER IF EXISTS on_developer_added_telegram ON public.developers;
CREATE TRIGGER on_developer_added_telegram AFTER INSERT ON public.developers FOR EACH ROW EXECUTE FUNCTION public.notify_telegram_master();

DROP TRIGGER IF EXISTS on_blog_added_telegram ON public.blog_posts;
CREATE TRIGGER on_blog_added_telegram AFTER INSERT ON public.blog_posts FOR EACH ROW EXECUTE FUNCTION public.notify_telegram_master();

-- Create chat_messages table if it doesn't exist (for the trigger)
CREATE TABLE IF NOT EXISTS public.chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT,
    user_message TEXT,
    bot_response TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

DROP TRIGGER IF EXISTS on_chat_added_telegram ON public.chat_messages;
CREATE TRIGGER on_chat_added_telegram AFTER INSERT ON public.chat_messages FOR EACH ROW EXECUTE FUNCTION public.notify_telegram_master();

-- 4. Create a Visitor Logs table for tracking and notify
CREATE TABLE IF NOT EXISTS public.visitor_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_path TEXT,
    user_agent TEXT,
    ip_address TEXT,
    referrer TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

DROP TRIGGER IF EXISTS on_visitor_added_telegram ON public.visitor_logs;
CREATE TRIGGER on_visitor_added_telegram AFTER INSERT ON public.visitor_logs FOR EACH ROW EXECUTE FUNCTION public.notify_telegram_master();

-- Add a generic trigger for any other potential tables
-- (Add more here if you have custom tables)

-- =====================================================
-- TEST SCRIPT
-- =====================================================
-- INSERT INTO leads (name, email, phone, source) VALUES ('Test From Supabase', 'test@example.com', '123456789', 'Direct SQL');
