-- =====================================================
-- BIN THANI REAL ESTATE - DATABASE SCHEMA
-- Run this in Supabase SQL Editor
-- =====================================================

-- Create properties table
CREATE TABLE IF NOT EXISTS properties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    price TEXT,
    price_numeric INTEGER,
    location TEXT,
    area_full TEXT,
    type TEXT,
    bedrooms INTEGER DEFAULT 0,
    bathrooms INTEGER DEFAULT 0,
    area TEXT,
    images JSONB,
    status TEXT DEFAULT 'Available',
    amenities JSONB,
    featured BOOLEAN DEFAULT false,
    developer TEXT,
    year_built INTEGER,
    parking INTEGER DEFAULT 0,
    furnished TEXT,
    floor_plan TEXT,
    google_maps_embed TEXT,
    views INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create leads table
CREATE TABLE IF NOT EXISTS leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    phone TEXT,
    email TEXT,
    interest TEXT,
    area TEXT,
    budget TEXT,
    message TEXT,
    source TEXT DEFAULT 'chatbot',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create blog_posts table
CREATE TABLE IF NOT EXISTS blog_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT,
    author TEXT DEFAULT 'Bin Thani Team',
    image TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE blog_posts ENABLE ROW LEVEL SECURITY;

-- Create policies for public read access
CREATE POLICY "Properties are viewable by everyone" ON properties
    FOR SELECT USING (true);

CREATE POLICY "Anyone can insert leads" ON leads
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Blog posts are viewable by everyone" ON blog_posts
    FOR SELECT USING (true);

-- Insert sample blog posts
INSERT INTO blog_posts (title, content, author, image) VALUES
('Top 10 Luxury Villas in Sharjah 2024', 'Discover the most prestigious villa communities in Sharjah...', 'Bin Thani Team', 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800'),
('Investment Opportunities in UAE Real Estate', 'Why now is the perfect time to invest in UAE property market...', 'Bin Thani Team', 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800'),
('Guide to Buying Off-Plan Properties', 'Everything you need to know about off-plan investments in UAE...', 'Bin Thani Team', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800');

-- Seed properties (if empty)
INSERT INTO properties (title, description, price, price_numeric, location, area_full, type, bedrooms, bathrooms, area, images, status, amenities, featured, developer, year_built, parking, furnished)
SELECT 
    'Luxury 6BR Villa - Al Jada',
    'Stunning 6-bedroom villa with private pool, smart home system, and panoramic views of Sharjah. Premium finishing with Italian marble floors.',
    'AED 7,500,000', 7500000, 'Al Jada, Sharjah', 'Al Jada, Sharjah', 'Villa', 6, 7, '6,500 sqft',
    '["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800"]',
    'Available', '["Private Pool", "Smart Home", "Home Cinema", "Gym", "Garden", "Parking"]', true, 'Arada', 2024, 3, 'Yes'
WHERE NOT EXISTS (SELECT 1 FROM properties WHERE title = 'Luxury 6BR Villa - Al Jada');

-- Add more properties as needed...

SELECT * FROM properties LIMIT 10;
SELECT * FROM leads LIMIT 10;
SELECT * FROM blog_posts;
